framework:
    messenger:
        # Uncomment this (and the failed transport below) to send failed messages to this transport for later handling.
        failure_transport: failed

        transports:
            # Define your async transport for regular messages
            async: '%env(MESSENGER_TRANSPORT_DSN)%'

            # Define a transport for handling failed messages
            failed: 'doctrine://default?queue_name=failed'
            # You can use any valid transport supported by Messenger, such as doctrine, amqp, etc.

        routing:
            # Route your regular messages to the async transport
            'App\Message\SmsNotification': async
